# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ch07-csy-webService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ch07-csy-webService
  pod 'Progress'

end
